### PR TITLE
openstack: enable openSUSE Leap 42.2

### PR DESCRIPTION
**Pull request by smithfarm**
Fixes: #29
Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
`ceph-workbench ceph-qa-suite -v --ceph-repo http://github.com/SUSE/ceph --ceph ses4-test --suite dummy qa/distros/all/opensuse_42.2.yaml`

**running** http://149.202.188.247:8081/

**Comment by smithfarm** [comment]
```
2017-02-22T14:31:30.062 INFO:teuthology.task.ansible.out:TASK [testnode : Install packages] *********************************************
Wednesday 22 February 2017  14:31:30 +0000 (0:00:00.420)       0:04:21.876 **** 

2017-02-22T14:31:30.243 INFO:teuthology.task.ansible.out:skipping: [target213032076195.teuthology] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
```

Need to look at why ceph-cm-ansible doesn't like openSUSE Leap 42.2

**Comment by jan--f** [comment]
Looks like ceph_cm_ansible doesn't know how to install packages with zypper.
https://github.com/ceph/ceph-cm-ansible/blob/master/roles/packages/tasks/packages.yml

**Comment by jan--f** [comment]
Something like
```
- name: Install or remove zypper packages
  zypper:
    update_cache: true
    name: "{{ item }}"
    state: "{{ state }}"
  with_items: "{{ zyp_packages }}"
  when: zyp_packages|length > 0 and
ansible_pkg_mgr == "zypper"
```

but it would need to be called with something like
```
ansible-playbook --extra-vars='{"zyp_packages": "foo"}'
```
and I don't know where that call would me made.

**Comment by smithfarm** [comment]
@jan--f Upstream ceph/ceph-cm-ansible does know how to install packages with zypper, just the package list for 42.2 was missing. Since getting patches into ceph-cm-ansible upstream can take time, i have taken to using this override:

https://github.com/SUSE/ceph/blob/ses4-test/qa/distros/all/opensuse_42.2.yaml

Here is the commit (from today) that fixes the problem on the ceph-cm-ansible side: https://github.com/SUSE/ceph-cm-ansible/commit/2c8bdec5d4355ed8ceb2c4b8b7266acda04a5d6a

So, the problem is fixed, if not in an ideal way.

**Comment by bmwiedemann** [comment]
you could also add
http://download.opensuse.org/repositories/Cloud:/Images:/Leap_42.3/images/openSUSE-Leap-42.3-OpenStack.x86_64.qcow2
if your software can live with it being updated until 42.3 is gold

**Pull request merged**
