### PR TITLE
orchestra/daemon: separate register_daemon from add_daemon

### PR DESCRIPTION
**Pull request by smithfarm**
The former registers without starting; the latter does both (as before).

Signed-off-by: Sage Weil <sage@redhat.com>
(cherry picked from commit 2bcf6fe1133042dfdfae12d2d299a9348467ab62)

### CODE REVIEW

**Comment by smithfarm** [comment]
The `ceph` task in ceph/ceph.git master has https://github.com/ceph/ceph/commit/fa0b2164 which depends on this upstream commit. Without it, all jobs that run the `ceph` task fail with:

```
     

2017-04-19T12:58:57.881 INFO:tasks.ceph:Starting mon daemons in cluster ceph...
2017-04-19T12:58:57.881 ERROR:teuthology.contextutil:Saw exception from nested tasks
Traceback (most recent call last):
  File "/home/ubuntu/teuthology/teuthology/contextutil.py", line 30, in nested
    vars.append(enter())
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/ubuntu/src/github.com_ovh_ceph_bp-fiemap-burden/qa/tasks/ceph.py", line 1148, in run_daemon
    ctx.daemons.register_daemon(
AttributeError: 'DaemonGroup' object has no attribute 'register_daemon'
```

**Comment by smithfarm** [comment]
Note: this is just a stopgap measure until I can get around to bringing downstream up-to-date with the current state of upstream master.

**Comment by smithfarm** [comment]
Test running at http://137.74.26.23:8081/ubuntu-2017-04-19_13:58:13-rados-bp-fiemap-burden---basic-openstack/

**Comment by branch-predictor** [comment]
This seems to be doing the trick.

**Pull request merged**
