### PR TITLE
openstack: add Leap 42.2 cloud image URL and fixed user-data

### PR DESCRIPTION
**Pull request by smithfarm**
Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
@dachary Not sure if teuthology-openstack can handle `.tbz` (and, indeed, I've never seen such an extension before)

**Comment by dachary** [comment]
What matters is to check if the file is .qcow2 the tbz suggests it's a tar.bz2 or something

**Comment by smithfarm** [comment]
@dachary Please re-review

**Comment by dachary** [comment]
testing at http://167.114.255.36:8081/ubuntu-2017-02-08_23:55:25-rados:basic-ses4-test---basic-openstack/

**Comment by dachary** [comment]
goot to merge when / if the test passes

**Comment by smithfarm** [comment]
@dachary Test failed, clicking on log gives 404

**Comment by smithfarm** [comment]
@dachary The teuthology VM needs to be built from this PR branch

**Comment by smithfarm** [comment]
Rebased.

**Comment by smithfarm** [comment]
test running here: http://137.74.30.98:8081/ubuntu-2017-02-09_12:20:42-rados:basic-ses4-test---basic-openstack/

**Comment by smithfarm** [comment]
@dachary Pushed a commit to address the test failure.

**Comment by smithfarm** [comment]
new test: http://213.32.78.168:8081/ubuntu-2017-02-09_13:44:08-rados:basic-ses4-test---basic-openstack/

**Comment by smithfarm** [comment]
Next failure is:

```
2017-02-09 23:19:27,307.307 INFO:teuthology.orchestra.run.target137074025048:Running: 'sudo zypper -n install --capability ceph-mgr'
2017-02-09 23:19:27,418.418 INFO:teuthology.orchestra.run.target137074025048.stdout:Loading repository data...
2017-02-09 23:19:27,442.442 INFO:teuthology.orchestra.run.target137074025051.stderr:No provider of 'ceph-mgr' found.
2017-02-09 23:19:27,693.693 INFO:teuthology.orchestra.run.target137074025048.stdout:Reading installed packages...
2017-02-09 23:19:28,442.442 INFO:teuthology.orchestra.run.target137074025048.stderr:No provider of 'ceph-mgr' found.
```

**Comment by smithfarm** [comment]
@dachary Latest test results are here: http://213.32.78.168:8081/ubuntu-2017-02-09_23:08:36-rados:basic-ses4-test---basic-openstack/

The reason it is trying to install `ceph-mgr` is because the job yaml includes:

```
suite_branch: master
suite_path: /home/ubuntu/src/github.com_ceph_ceph_master/qa
```

However, this should not be the case with the command I'm using: `ceph-workbench ceph-qa-suite -v    --simultaneous-jobs 20     --teuthology-git-url http://github.com/SUSE/teuthology     --teuthology-branch wip-leap-42-2     --suite rados/basic     --ceph-git-url http://github.com/SUSE/ceph     --ceph ses4-test     --limit 1 qa/distros/all/opensuse_42.1.yaml`

**Comment by smithfarm** [comment]
@dachary I suggest we merge this one and open a new PR for the suite branch/URL handling.

**Comment by dachary** [comment]
@smithfarm ok !

**Pull request merged**
