### PR TITLE
buildpackages: import from ceph/master

### PR DESCRIPTION
**Pull request by dachary**
It is exactly the same in all branches. It really belongs in teuthology
and was placed in ceph-qa-suite because it required a more flexible
development cycle.

Signed-off-by: Loic Dachary <loic@dachary.org>

### CODE REVIEW

**Comment by dachary** [comment]
@smithfarm I think we can merge that as is. It's currently broken all over the place. And it will not interfere with anything else.

**Comment by smithfarm** [comment]
@dachary Would it be better to take the version from here [1] ? We have it working at least for SUSE.

[1] https://github.com/SUSE/ceph-qa-suite/tree/wip-opensuse-jewel/suites/buildpackages

**Comment by smithfarm** [comment]
@dachary It's not quite true that it won't interfere, because we will need it in order to run any tests.

**Comment by dachary** [comment]
e9942b5 has the changes from https://github.com/SUSE/ceph-qa-suite/tree/wip-opensuse-jewel/suites/buildpackages

**Comment by dachary** [comment]
> @dachary It's not quite true that it won't interfere, because we will need it in order to run any tests.

I meant that it wont break it more than it currently is ;-)

**Comment by smithfarm** [comment]
@dachary What was the "branch specification" that you omitted?

**Comment by dachary** [comment]
```
--- /home/loic/software/ceph/ceph/qa/tasks/buildpackages/common.sh	2017-02-07 22:19:03.773359472 +0100
+++ /home/loic/software/ceph/ceph-qa-suite/tasks/buildpackages/common.sh	2017-02-07 22:17:38.081493654 +0100
@@ -15,7 +15,7 @@
 # GNU Library Public License for more details.
 #
 function install_deps() {
-    git archive --remote=git://git.ceph.com/ceph.git master install-deps.sh | tar -xvf -
+    git archive --remote=git://git.ceph.com/ceph.git jewel install-deps.sh | tar -xvf -
     #
     # drop the following hack when trusty is not supported anymore
     # there is no other way as long as we maintain a debian directory that tries

```

**Comment by dachary** [comment]
this will need to be fixed, i.e. buildpackages will need to figure out which branch to use. But that's a fix we can do after it is merged. My goal is merely to collect the most up to date version and move it here.

**Pull request merged**
