### PR TITLE
clock: use ntpq instead of ntpdc

### PR DESCRIPTION
**Pull request by smithfarm**
Newer versions of ntpd have ntpdc support turned off by default,
to avoid NTP reflection/amplification.

See, e.g., https://mail-index.netbsd.org/netbsd-users/2015/08/04/msg016612.html

Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
**running** http://137.74.27.194:8081/ubuntu-2017-02-11_17:29:38-rados:basic-ses4-test---basic-openstack/

**Comment by smithfarm** [comment]
Initial clock skew doesn't look good:

```
2017-02-11T18:02:55.176 INFO:teuthology.task.clock:Checking initial clock skew...
2017-02-11T18:02:55.176 INFO:teuthology.orchestra.run.target149202164022:Running: 'PATH=/usr/bin:/usr/sbin ntpq -p'
2017-02-11T18:02:56.530 INFO:teuthology.orchestra.run.target149202164022.stdout:     remote           refid      st t when poll reach   delay   offset  jitter
2017-02-11T18:02:56.531 INFO:teuthology.orchestra.run.target149202164022.stdout:==============================================================================
2017-02-11T18:02:56.531 INFO:teuthology.orchestra.run.target149202164022.stdout: vps3.drown.org  17.253.2.253     2 u    2   64    1  109.724  555.611   0.000
2017-02-11T18:02:56.531 INFO:teuthology.orchestra.run.target149202164022.stdout: ntp2.wiktel.com .INIT.          16 u    -   64    0    0.000    0.000   0.000
2017-02-11T18:02:56.531 INFO:teuthology.orchestra.run.target149202164022.stdout: wanderportips03 45.79.182.100    3 u    3   64    1   71.956  550.713   0.000
2017-02-11T18:02:56.532 INFO:teuthology.orchestra.run.target149202164022.stdout: triton.ellipse. 216.229.0.179    2 u    3   64    1  124.811  563.986   0.000
2017-02-11T18:02:56.533 INFO:teuthology.orchestra.run.target149202164207:Running: 'PATH=/usr/bin:/usr/sbin ntpq -p'
2017-02-11T18:02:57.644 INFO:teuthology.orchestra.run.target149202164207.stdout:     remote           refid      st t when poll reach   delay   offset  jitter
2017-02-11T18:02:57.645 INFO:teuthology.orchestra.run.target149202164207.stdout:==============================================================================
2017-02-11T18:02:57.646 INFO:teuthology.orchestra.run.target149202164207.stdout: ada.selinc.com  .GPS.            1 u    3   64    1  146.277  400.549   0.000
2017-02-11T18:02:57.647 INFO:teuthology.orchestra.run.target149202164207.stdout: srv2.us.inu.io  108.61.56.35     3 u    3   64    1  109.746  398.193   0.000
2017-02-11T18:02:57.647 INFO:teuthology.orchestra.run.target149202164207.stdout: int42.org       64.113.32.5      2 u    2   64    1  111.377  402.634   0.000
2017-02-11T18:02:57.647 INFO:teuthology.orchestra.run.target149202164207.stdout: pacific.latt.ne 68.110.9.223     2 u    3   64    1  167.502  409.649   0.000
```

**Comment by smithfarm** [comment]
Much better!

```
2017-02-11T21:24:11.494 INFO:teuthology.task.clock:Checking initial clock skew...
2017-02-11T21:24:11.494 INFO:teuthology.orchestra.run.target137074026182:Running: 'PATH=/usr/bin:/usr/sbin ntpq -p'
2017-02-11T21:24:12.445 INFO:teuthology.orchestra.run.target137074026182.stdout:     remote           refid      st t when poll reach   delay   offset  jitter
2017-02-11T21:24:12.446 INFO:teuthology.orchestra.run.target137074026182.stdout:==============================================================================
2017-02-11T21:24:12.447 INFO:teuthology.orchestra.run.target137074026182.stdout: ec2-54-236-224- .INIT.          16 u    -   64    0    0.000    0.000   0.000
2017-02-11T21:24:12.447 INFO:teuthology.orchestra.run.target137074026182.stdout: wanderportips03 .INIT.          16 u    -   64    0    0.000    0.000   0.000
2017-02-11T21:24:12.448 INFO:teuthology.orchestra.run.target137074026182.stdout: hadb1.smatwebde 216.229.0.179    2 u    1   64    1  111.429    5.109   0.000
2017-02-11T21:24:12.449 INFO:teuthology.orchestra.run.target137074026182.stdout: clock.trit.net  216.218.192.202  2 u    2   64    1  170.917   -0.236   0.000
2017-02-11T21:24:12.449 INFO:teuthology.orchestra.run.target137074026186:Running: 'PATH=/usr/bin:/usr/sbin ntpq -p'
2017-02-11T21:24:12.963 INFO:teuthology.orchestra.run.target137074026186.stdout:     remote           refid      st t when poll reach   delay   offset  jitter
2017-02-11T21:24:12.967 INFO:teuthology.orchestra.run.target137074026186.stdout:==============================================================================
2017-02-11T21:24:12.968 INFO:teuthology.orchestra.run.target137074026186.stdout: time.tritn.com  .INIT.          16 u    -   64    0    0.000    0.000   0.000
2017-02-11T21:24:12.968 INFO:teuthology.orchestra.run.target137074026186.stdout: wanderportips03 .INIT.          16 u    -   64    0    0.000    0.000   0.000
2017-02-11T21:24:12.968 INFO:teuthology.orchestra.run.target137074026186.stdout: hadb1.smatwebde .INIT.          16 u    -   64    0    0.000    0.000   0.000
2017-02-11T21:24:12.969 INFO:teuthology.orchestra.run.target137074026186.stdout: clock.trit.net  .INIT.          16 u    -   64    0    0.000    0.000   0.000
```

**Comment by smithfarm** [comment]
This is not good, however:

```
ubuntu@target137074026186:~> cat /etc/resolv.conf
nameserver 137.74.27.194
search
domain
```

**Comment by smithfarm** [comment]
@dachary I added 3 more commits since your review - please have another look. The latest state of this PR was tested at http://137.74.27.194:8081/ubuntu-2017-02-11_21:13:58-rados:basic-ses4-test---basic-openstack/ (without the SUSE/ceph-cm-ansible patches, but apparently the tests can limp along with unparseable `/etc/resolv.conf` ??)

**Comment by dachary** [comment]
:+1:

**Comment by smithfarm** [comment]
By "limping along with unparseable `/etc/resolv.conf` I mean this:

```
ubuntu@target149202188037:~> cat /etc/resolv.conf
nameserver 137.74.27.194
search 
domain 
ubuntu@target149202188037:~> ping teuthology
PING teuthology (127.0.1.1) 56(84) bytes of data.
64 bytes from teuthology.localdomain (127.0.1.1): icmp_seq=1 ttl=64 time=0.092 ms
64 bytes from teuthology.localdomain (127.0.1.1): icmp_seq=2 ttl=64 time=0.099 ms
^C
--- teuthology ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 0.092/0.095/0.099/0.010 ms
ubuntu@target149202188037:~> host teuthology
host: parse of /etc/resolv.conf failed
```

**Pull request merged**
