### PR TITLE
openstack: prefer vps-ssd-* flavors in OVH

### PR DESCRIPTION
**Pull request by smithfarm**
Fixes: https://github.com/SUSE/teuthology/issues/75

### CODE REVIEW

**Comment by smithfarm** [comment]
packages-repository still gets `hg-7-ssd-flex` - trying to understand why

**Comment by smithfarm** [comment]
oh, it's because the buildpackages task bypasses this logic and calls openstack.flavor directly - need to replicate the logic there, too.

**Comment by smithfarm** [comment]
@jan--f @dachary The first version didn't work, so I rewrote it. It's now more complicated but it works, and all the flavor selection code is now in only one place (before it was more-or-less duplicated in `openstack/__init__.py` and `task/buildpackages.py`).

Also, I couldn't figure out how to make two `flavor()` methods (one in `OpenStack` and another in `TeuthologyOpenStack`) play well together, so I changed the latter one to `_flavor()`. I went through the existing code and AFAICT it is only called from `create_cluster()` and nowhere else.

**Comment by smithfarm** [comment]
Tested - `packages-repository` gets `vps-ssd-3` now, and the build machine `ceph-rpm-...` gets `hg-60-ssd` as before.

**Comment by jan--f** [comment]
First of all, it seems to work alright...so there's that :)

Just from looking at it I think you could do the following:

- Put the logic from the OpenStacks ```flavor``` method in to a private* method called ```__flavor``` and change the class-internal calls accordingly.
- You'll still need a public ```flavor``` method because it is called from teuthology/provision/openstack.py but it only does ```return self.__flavor()```
- Then your TeuthologyOpenStack instance can use the ```flavor``` method but still call ```super.flavor_wrapper``` since this now calls the OpenStack private method ```__flavor```

Beware this is all in my head...haven't actually tried it ;) Also not sure this improves things massively...in an ideal world we might reconsider this class hierarchy.

* Another thing to keep in mind: naming a method __foo doesn't actually make it private. Python only mangles the name a bit (_ClassName_foo or something of the sort), but this should suffice here.

**Comment by smithfarm** [comment]
@jan--f: Thanks! That gave me some more ideas :-) Also, I found two problems with the patch:

1. test target VMs provisioned from `teuthology/provision/openstack.py` were not benefiting from the improved flavor selection heuristics
2. I found yet another place where the OVH flavor selection regex was duplicated (setup-openstack.sh).

Pushed a new version of the patch and will run more tests.

**Comment by smithfarm** [comment]
Thanks @dachary - tracking your proposed enhancement at https://github.com/SUSE/teuthology/issues/79

**Pull request merged**
