### PR TITLE
Rebase to ceph/master

### PR DESCRIPTION
**Pull request by smithfarm**

### CODE REVIEW

**Comment by smithfarm** [comment]
@ldachary @dachary Please take a look.

I got the commits to cherry-pick from here: http://paste2.org/Z7ej2vW7

And the following commits may have had conflicts or already been cherry-picked to dachary openstack:

```
$ git cherry wip-ceph-master ceph-master master | grep -v '^-'
+ fc503de980db7084e1079659ea3e0ef468017ba6
+ 6f62faad6e267e73cf9522ea3c2c2ee385153d8b
+ 977e6f4f5e4a8cb3c91a7ee40e9d0d7bd61fd310
+ 5be63287b90335d4a04ef7bc2ef954affa0fe6bd
+ b27f3a581ef055040e4fbfd192be3e94a911738f
+ 51df83c0491a9320976454c22a6d58ffdce97269
+ c7302021bdede5f799ebe6f56d7d788d6ced0a1d
+ 87caf370b5aca220f150ecad7444ad4748601eb1
+ 7bb3b07f11025a17af209f87a1820751b702b3e6
+ 2191e2189066940b802a456e171cac4098452c54
+ ca9e2572ba90183c67a4da18487537386bdf84af
+ bc7b23f00eb3acc5d64d6063c194ce38cf15ba70
+ a4cf86367d5d5157b78a58d13239a12b1948b8ec
+ 7b0cf14ca4ded10e102786d9d6a41a8251cc4d73
+ 9478bc7d069350180cba13479280964479988180
+ 21ceb15e4005064edb52405efdb603ef131638b7
+ 571df61239bf7447b3fff3aa74552d3c540057e6
+ e5b1ead4a438a79427eb210787f0d98a90d14531
+ 082f4c17dc739407caf3affe7f6f8fddbe73fef8
+ 8ad5b2b82ca69df93ee1032131b3cc432c0bacb2
+ f7959ed37565c5f3e6b5ca376629678ad4550fc3
+ 0986c3276de01e2e9864f860139d6bb4d1ab931d
+ fda11cf203b8d097f968b4df46d125fbbcac49ae
+ 4ea434fc5f8972def50b6d8ae42560c3a65b1c34
+ 99235a00366e84e8eefe495ab99c7f6aa767a58d
+ 1232d9d2dd43e180f113f42b07531705d7f30a7c
```

**Comment by smithfarm** [comment]
I don't expect it to work, but I'm going to give it a try so we can start debugging.

**Comment by smithfarm** [comment]
@jan--f @rjfd JFYI

@dachary It seems to not like this line of the `setup.py` file:

```
openstacksdk!=0.9.11,!=0.9.12,>=0.9.10
```

**Comment by dachary** [comment]
going this way is really difficult. It's a lot easier to cherry-pick the commits unique to SUSE/teuthology/master on top of ceph/teuthology/master, because we authored them and know what to do to adapt.

**Comment by dachary** [comment]
not such a bad idea after all because of the many file renaming which complicate rebasing the other way around

**Comment by dachary** [comment]
* The diff from of my branch: git diff 27e284f5 loic/openstack  http://paste2.org/HJwfHBYF
* The diff of this pull request : git diff ceph/master suse/wip-ceph-master http://paste2.org/jaBD3Faj
* The diff of suse master branch : git diff 27e284f5 suse/master http://paste2.org/dYhNAM40

**Comment by dachary** [comment]
The following hunk does not seem to belong :+1: 

diff --git a/teuthology/matrix.py b/teuthology/matrix.py
index f4d91a58..956425d6 100644
--- a/teuthology/matrix.py
+++ b/teuthology/matrix.py
@@ -318,9 +318,7 @@ def generate_desc(joinf, result):
     Generates the text description of the test represented by result
     """
     if type(result) is frozenset:
-        ret = []
-        for i in sorted(result):
-            ret.append(generate_desc(joinf, i))
+        ret = sorted([generate_desc(joinf, i) for i in result])
         return '{' + ' '.join(ret) + '}'
     elif type(result) is tuple:
         (item, children) = result

**Comment by smithfarm** [comment]
@dachary 3506819 was cherry-picked in #2

**Comment by dachary** [comment]
The following is verified to be in nuke/__init__.py instead of nuke.py

```
diff --git a/teuthology/nuke.py b/teuthology/nuke.py
index c8abf21f..4033c4f9 100644
--- a/teuthology/nuke.py
+++ b/teuthology/nuke.py
@@ -443,7 +443,7 @@ def stale_openstack_instances(ctx, instances, locked_nodes):
 
 
 def openstack_delete_volume(id):
-    sh("openstack volume delete " + id + " || true")
+    OpenStack().run("volume delete " + id + " || true")
 
 
 def stale_openstack_volumes(ctx, volumes):
@@ -451,8 +451,8 @@ def stale_openstack_volumes(ctx, volumes):
     for volume in volumes:
         volume_id = volume.get('ID') or volume['id']
         try:
-            volume = json.loads(sh("openstack volume show -f json " +
-                                   volume_id))
+            volume = json.loads(OpenStack().run("volume show -f json " +
+                                                volume_id))
         except subprocess.CalledProcessError:
             log.debug("stale-openstack: {id} disappeared, ignored"
                       .format(id=volume_id))

```

**Comment by dachary** [comment]
The files in teuthology/openstack are ignored when comparing the diff, the suse version should be considered authoritative but I'll check for patches that may have been done in ceph/master

**Comment by dachary** [comment]
:+1: after comparing 

- The diff of this pull request : git diff ceph/master suse/wip-ceph-master http://paste2.org/jaBD3Faj
- The diff of suse master branch : git diff 27e284f suse/master http://paste2.org/dYhNAM40

Now proceeding to compare the content of the openstack directory

**Comment by dachary** [comment]
git diff suse/master suse/wip-ceph-master -- teuthology/openstack

```
diff --git a/teuthology/openstack/openstack-opensuse-42.1-user-data.txt b/teuthology/openstack/openstack-opensuse-42.1-user-data.txt
index f928c78a..08104770 100644
--- a/teuthology/openstack/openstack-opensuse-42.1-user-data.txt
+++ b/teuthology/openstack/openstack-opensuse-42.1-user-data.txt
@@ -2,7 +2,7 @@
 bootcmd:
  - echo nameserver {nameserver} | tee /etc/resolv.conf
  - echo search {lab_domain} | tee -a /etc/resolv.conf
- - sed -ie 's/PEERDNS="yes"/PEERDNS="no"/' /etc/sysconfig/network-scripts/ifcfg-eth0
+ - sed -ie 's/PEERDNS="yes"/PEERDNS="no"/' /etc/sysconfig/network/ifcfg-eth0
  - ( curl --silent http://169.254.169.254/2009-04-04/meta-data/hostname | sed -e 's/[\.-].*//' ; eval printf "%03d%03d%03d%03d.{lab_domain}" $(curl --silent http://169.254.169.254/2009-04-04/meta-data/local-ipv4 | tr . ' ' ) ) | tee /etc/hostname
  - hostname $(cat /etc/hostname)
  - ( echo ; echo "MaxSessions 1000" ) >> /etc/ssh/sshd_config
```

**Comment by smithfarm** [comment]
@dachary The change in openstack-opensuse-42.1-user-data.txt is from 2d71e451 which may not have been upstreamed yet.

**Comment by dachary** [comment]
With 3044606 and 94974ed tox -v -e openstack passes except for test_create. I won't fix it right now though as it most certainly is a test problem and not an actual problem.

**Comment by dachary** [comment]
I think the next step is either to merge or to add the buildpackages pull request here and keep going.

**Pull request merged**
