### PR TITLE
openstack: allow setting of teuthology VM params from command line

### PR DESCRIPTION
**Pull request by smithfarm**
Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
you may want to add "s1-*" and "c2-*" instance to filter list, so it won't break once ovh deprecates old vps flavors

**Comment by jan--f** [comment]
dummy suite with teuthology checked out to this branch doesn't blow up.
http://149.202.184.202:8081/ubuntu-2017-04-18_18:08:29-dummy-ses4---basic-openstack/

**Comment by smithfarm** [comment]
Changelog:

* add new OVH flavors in `setup-openstack.sh` and buildpackages task as well.

**Comment by smithfarm** [comment]
Changelog: added the new `--controller-foo` options to the list of options to delete before passing to `t-s`

**Comment by smithfarm** [comment]
`ceph-workbench ceph-qa-suite -v --ceph-repo http://github.com/SUSE/ceph --ceph ses5 --suite dummy --controller-cpus 3 --controller-ram 13000 --controller-disk 50 qa/distros/all/sle_12.2.yaml`

**running** http://158.69.90.23:8081/ubuntu-2017-04-25_08:55:45-dummy-ses5---basic-openstack/

**Pull request merged**
