### PR TITLE
openstack: user-data: add filesystems:ceph:mimic OBS repo

### PR DESCRIPTION
**Pull request by smithfarm**
Temporary measure to make it possible for DeepSea to deploy Ceph
in openSUSE Leap 15.0

References: https://github.com/SUSE/DeepSea/issues/979
Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by kshtsk** [comment]
@smithfarm why not using --test-repo for this purpose?

**Comment by kshtsk** [comment]
```--test-repo ceph-mimic:https://download.opensuse.org/repositories/filesystems:ceph:mimic/openSUSE_Leap_15.0/filesystems:ceph:mimic.repo```

**Comment by kshtsk** [comment]
@smithfarm oh... I see, `--test-repo` disables buildpackages. This is good example why we do need `--buildpackages` option.

**Comment by smithfarm** [comment]
@kshtsk I agree using user-data for this purpose is not ideal.

**Pull request merged**
