### PR TITLE
tests: fix openstack-integration test suite

### PR DESCRIPTION
**Pull request by smithfarm**

### CODE REVIEW

**Comment by dachary** [comment]
> Am I supposed to "source openrc.sh" on the remote teuthology machine before running the integration tests?

Yes. But you should not need to because the .bashrc should be set to do it as soon as you log in. If not, something went wrong during the initialization of the cluster.

**Comment by smithfarm** [comment]
@dachary I verified that the `OS_*` environment variable are populated before running `tox -v -e py27 -- teuthology/openstack/test/openstack-integration.py::TestSuite::test_suite_noop` but it looks to me like tox is using its own pristine environment where these variables are missing.

**Comment by smithfarm** [comment]
I see that `[testenv:py27-integration]` does `passenv = HOME OS_REGION_NAME OS_AUTH_URL OS_TENANT_ID OS_TENANT_NAME OS_PASSWORD OS_USERNAME` . . . however, when I do `tox -v -e py27-integration -- teuthology/openstack/test/openstack-integration.py::TestSuite::test_suite_noop` the noop test fails *and* hangs. I get:

```
...
teuthology/openstack/test/openstack-integration.py::TestSuite::test_suite_noop FAILED
```

followed by a very long wait (I'm letting it run now. . .) Any idea how to debug this?

**Comment by dachary** [comment]
Add a -s to see the output in real time (this is a pytest flag)

```
tox -v -e py27-integration -- -s teuthology/openstack/test/openstack integration.py::TestSuite::test_suite_noop
```

**Comment by dachary** [comment]
and -v as well (in addition to -s )

**Comment by smithfarm** [comment]
@dachary It seems teuthology-suite changed the way it parses arguments.

**Comment by smithfarm** [comment]
@dachary This fixes the noop test

**Comment by smithfarm** [comment]
This appears to fix the entire openstack-integration test suite. Re-running it to make sure.

**Comment by smithfarm** [comment]
```
  openstack-integration: commands succeeded
  congratulations :)
```

**Comment by smithfarm** [comment]
Dropping 3210fd2289625bc15f4123919609ef29077734b1 and merging.

**Comment by smithfarm** [comment]
@dachary I guess these tests could be added to the "teuthology" suite.

**Pull request merged**
