### PR TITLE
salt: rip it out

### PR DESCRIPTION
**Pull request by smithfarm**
This stuff is not upstreamable, so rip it out after copying all the
good parts to the ceph repo (salt.py and salt_manager.py in qa/tasks)
for both SES5 and SES6.

Companion PRs:
* SES6: https://github.com/SUSE/ceph/pull/209 (merged)
* DeepSea master: https://github.com/SUSE/DeepSea/pull/1394 (merged)
* SES5: https://github.com/SUSE/ceph/pull/245 (merged)
* DeepSea SES5: https://github.com/SUSE/DeepSea/pull/1566 (merged)

- [x] open DeepSea SES5 PR
- [x] merge DeepSea SES5 PR
- [x] remove DNM
- [ ] merge this PR

### CODE REVIEW

**Comment by smithfarm** [comment]
To be tested and merged together with https://github.com/SUSE/ceph/pull/209

**Comment by kshtsk** [comment]
retest this please

**Comment by kshtsk** [comment]
retest this please

**Comment by kshtsk** [comment]
retest this please

**Comment by kshtsk** [comment]
retest this please

**Comment by kshtsk** [comment]
@smithfarm can we abandon this PR already?

**Comment by smithfarm** [comment]
> @smithfarm can we abandon this PR already?

No, please keep it open.

**Comment by smithfarm** [comment]
@kshtsk This should be ready to go. Can you trigger the functional tests?

**Comment by smithfarm** [comment]
@susebot run teuthology with deepsea:tier0

**Pull request merged**
