### PR TITLE
Wip matrix tostr

### PR DESCRIPTION
**Pull request by kshtsk**

### CODE REVIEW

**Comment by kshtsk** [comment]
@susebot run teuthology for suse:tier0

**Comment by kshtsk** [comment]
@susebot run teuthology for suse:tier0

**Comment by kshtsk** [comment]
susebot run teuthology for suse:tier0

**Comment by kshtsk** [comment]
@susebot run teuthology for suse:tier0

**Comment by kshtsk** [comment]
@susebot run teuthology for suse:tier0

**Comment by kshtsk** [comment]
the teuthology suse:tier0 test was actually passed

**Comment by kshtsk** [comment]
@susebot run teuthology for suse:tier0

**Comment by kshtsk** [comment]
@susebot run teuthology for suse:tier0

**Comment by kshtsk** [comment]
@susebot run teuthology for suse:tier0

**Comment by kshtsk** [comment]
@susebot run teuthology for suse:tier0

**Comment by kshtsk** [comment]
@susebot run teuthology for suse:tier0

**Comment by kshtsk** [comment]
@susebot run teuthology for suse:tier0

**Comment by smithfarm** [comment]
@kshtsk What is the reason for including the first commit (`$` magical character for random distro)? TBH I am not fond of this feature. See http://tracker.ceph.com/issues/35951 for why.

(I prefer to have functioning `--filter` and do without `$`)

**Comment by kshtsk** [comment]
> @kshtsk What is the reason for including the first commit (`$` magical character for random distro)? TBH I am not fond of this feature. See http://tracker.ceph.com/issues/35951 for why.
> 
The reason of including it is to smooth cherry pick of matrix fix from upstream, otherwise merge is required. Another good thing is to make downstream close to upstream as much as possible. I'm not advocating for this commit in particular I don't see any value for it in sense of teuthology user.
> (I prefer to have functioning `--filter` and do without `$`)
No comments, I'm not aware of why they pushed '$' feature to upstream.

@smithfarm what is wrong with this code, it is breaking downstream functionality somehow?

**Comment by kshtsk** [comment]
@smithfarm do you know if they provided a fix for http://tracker.ceph.com/issues/35951 ?

**Comment by smithfarm** [comment]
@kshtsk As far as I know, there is no easy fix for http://tracker.ceph.com/issues/35951 and, as far as I can tell, it's still assigned to the person who implemented the `$` feature.

I really would prefer to *not* backport the `$` feature to our teuthology branch.

**Comment by kshtsk** [comment]
> @kshtsk As far as I know, there is no easy fix for http://tracker.ceph.com/issues/35951 and, as far as I can tell, it's still assigned to the person who implemented the `$` feature.
> 
> I really would prefer to _not_ backport the `$` feature to our teuthology branch.

@smithfarm Yeah, seems like I harried to fix the RandomMatrix upstream, so... I'll drop this commit and make a separate patch for matrix tostr.

**Comment by kshtsk** [comment]
@susebot run teuthology for suse:tier0

**Comment by kshtsk** [comment]
@smithfarm ping

**Pull request merged**
