### PR TITLE
install: work around mozilla-nss/libfreebl3 issue

### PR DESCRIPTION
**Pull request by smithfarm**
ceph-test requires mozilla-nss, which might not be installable if
newer libfreebl3 is already present in the system. This is a
realistic possibility because chrony requires libfreebl3. Now, of
course, mozilla-nss provides libfreebl3 but if a newer libfreebl3
is already present, we cannot install mozilla-nss.

Also: if the rpm array is populated, we *presumably* always want
to install those rpms, so change the conditional so it checks rpm
instead of system_pkglist.

Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
@susebot run teuthology suse/tier0

**Comment by smithfarm** [comment]
@jschmid1 @kshtsk This is not a permanent solution for the issue - just a workaround. The problem is that the JeOS images we are using often contain newer packages than are in the official SLE repos. In this case, the package is "libfreebl3" which is a subpackage of mozilla-nss.

Sigh.

**Comment by smithfarm** [comment]
Eventually the problem will go away (when the newer mozilla-nss and its subpackages hits the update channels). Then we can drop this workaround.

**Comment by kshtsk** [comment]
Since it is a temporary solution I would avoid to merge it now, I can switch the main teuthology to this branch until newer mozilla-nss appeared.

**Comment by kshtsk** [comment]
Closing ticket, since the issue went away after syncing update repos.

**Pull request closed without merging**
