### PR TITLE
misc.py: saner write_file() and sudo_write_file()

### PR DESCRIPTION
**Pull request by smithfarm**
This runs on the test node, which might not have Python 2.

Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
ah, should have just tested it on my laptop:

```
smithfarm@wilbur:~> sudo python3 -c 'import shutil, sys; shutil.copyfileobj(sys.stdin, file(sys.argv[1], "wb"))' typescript
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'file' is not defined
```

**Comment by smithfarm** [comment]
https://stackoverflow.com/questions/28121163/python-3-doesnt-have-the-file-function

**Comment by smithfarm** [comment]
Now it says:

```
2018-03-02T15:58:00.467 INFO:teuthology.orchestra.run.target149202191111:Running: 'sudo python3 -c \'import shutil, sys; shutil.copyfileobj(sys.stdin, open(sys.argv[1], "wb"))\' /etc/rsyslog.d/80-cephtest.conf'
2018-03-02T15:58:00.618 INFO:teuthology.orchestra.run.target149202191111.stderr:Traceback (most recent call last):
2018-03-02T15:58:00.618 INFO:teuthology.orchestra.run.target149202191111.stderr:  File "<string>", line 1, in <module>
2018-03-02T15:58:00.618 INFO:teuthology.orchestra.run.target149202191111.stderr:  File "/usr/lib64/python3.6/shutil.py", line 82, in copyfileobj
2018-03-02T15:58:00.619 INFO:teuthology.orchestra.run.target149202191111.stderr:    fdst.write(buf)
2018-03-02T15:58:00.619 INFO:teuthology.orchestra.run.target149202191111.stderr:TypeError: a bytes-like object is required, not 'str'
```

**Comment by smithfarm** [comment]
https://stackoverflow.com/questions/33054527/python-3-5-typeerror-a-bytes-like-object-is-required-not-str-when-writing-t

**Comment by smithfarm** [comment]
This version works, at least for writing text files. Afaict, in Python 2 the "b" (for "bytes" or "binary"?) can be used for any data - binary or text - whereas in Python 3 this is no longer the case. (?)

**Comment by smithfarm** [comment]
This function `write_file()` . . . all it does is take a variable with some data in it, and writes it out as a file on the test node. Kind of like `echo "$VAR" > somefile` except "somefile" resides on a remote machine.

I'm not sure why they need to run a python interpreter on the remote machine to get this done, though.

**Comment by kshtsk** [comment]
@smithfarm First, I don't know too why they use such kind of complication. This is really crazy/lazy idea to use python to write file on remote node. I would suggest to refactor this code at least to use 'cat'. But in the ideal world, from my point of view, it is the best to use 'scp' to write/read files remotely.

**Comment by kshtsk** [comment]
@smithfarm And when I said 'scp' I didn't mean to run it as shell command, I meant protocol.

**Comment by smithfarm** [comment]
@kshtsk Yes, it's bizarre. I can only guess that the shell redirect does not work as expected when executed via `remote.run()` - see the code comments in teuthology/orchestra/run.py - but I'll give "cat" a try.

**Comment by smithfarm** [comment]
Ah, I see this code is very, very old

```
^7d4bb120 (Tommi Virtanen  2011-05-31 13:51:48 -0700  504)             'import shutil, sys; shutil.copyfileobj(sys.stdin, file(sys.argv[1], "wb"))',
```

**Comment by smithfarm** [comment]
How's this for bizarre?

```
2018-03-02T22:37:50.024 INFO:teuthology.orchestra.run.target149202183204:Running: 'sudo cat > /etc/rsyslog.d/80-cephtest.conf'
2018-03-02T22:37:50.096 INFO:teuthology.orchestra.run.target149202183204.stderr:bash: /etc/rsyslog.d/80-cephtest.conf: Permission denied
```

(But it works with the python kludge)

**Comment by kshtsk** [comment]
@smithfarm Don't you think 'cat  - > file' should be quoted?

**Comment by smithfarm** [comment]
Turns out "sudo cat > /etc/foo" does not work, because the redirection is not done by sudo. Fixing.

**Comment by kshtsk** [comment]
@smithfarm what about using 'tee'? or a combination of 'cat >/tmp' && sudo mv

**Comment by kshtsk** [comment]
@smithfarm another one workaround is to use shell instead of python `sudo sh -c 'cat - > /filepath'`

**Comment by smithfarm** [comment]
w00t, appears to work:

```
2018-03-02T22:55:55.975 INFO:teuthology.orchestra.run.target149202184007:Running: "sudo sh -c 'cat > /etc/rsyslog.d/80-cephtest.conf'"
```

passes without error

**Comment by smithfarm** [comment]
OK, this seems to be ready.

**Pull request merged**
